// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jfAhwLt0foVFAuMxL1OlXxe_5E5qpbA',
    appId: '1:303868800965:web:c5fb23e9601456912125ac',
    messagingSenderId: '303868800965',
    projectId: 'coffee-mate-f7ad9',
    authDomain: 'coffee-mate-f7ad9.firebaseapp.com',
    storageBucket: 'coffee-mate-f7ad9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshjQ1CAD_F8m-lgLW4Jzb0ZjCsBLNt_Q',
    appId: '1:303868800965:android:371b28cbb308a7262125ac',
    messagingSenderId: '303868800965',
    projectId: 'coffee-mate-f7ad9',
    storageBucket: 'coffee-mate-f7ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqnYoGpc1GbQP2uvjEL9WgvChYGpNaEvc',
    appId: '1:303868800965:ios:fedd1867cfe48b1c2125ac',
    messagingSenderId: '303868800965',
    projectId: 'coffee-mate-f7ad9',
    storageBucket: 'coffee-mate-f7ad9.firebasestorage.app',
    iosBundleId: 'com.example.yenebuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-afQh6fUlzi4e4nFRUdfU9bp5sjsbtBA',
    appId: '1:769307769254:ios:8409bd91dff38095b0f767',
    messagingSenderId: '769307769254',
    projectId: 'chatapp-db23a',
    databaseURL: 'https://chatapp-db23a-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-db23a.firebasestorage.app',
    iosBundleId: 'com.example.yenebuna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02PyFC7IAV63NwoQHMw9WG3mjIfzI1Hw',
    appId: '1:769307769254:web:5a15c6ebb0eea99db0f767',
    messagingSenderId: '769307769254',
    projectId: 'chatapp-db23a',
    authDomain: 'chatapp-db23a.firebaseapp.com',
    databaseURL: 'https://chatapp-db23a-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-db23a.firebasestorage.app',
  );

}